-- Καθαρισμός πίνακα πριν την εισαγωγή
DELETE FROM nationality;

INSERT INTO nationality (name) VALUES ('Αγία Λουκία');
INSERT INTO nationality (name) VALUES ('Άγιος Βικέντιος και Γρεναδίνες');
INSERT INTO nationality (name) VALUES ('Άγιος Μαρίνος');
INSERT INTO nationality (name) VALUES ('Άγιος Χριστόφορος και Νέβις');
INSERT INTO nationality (name) VALUES ('Αζερμπαϊτζάν');
INSERT INTO nationality (name) VALUES ('Αίγυπτος');
INSERT INTO nationality (name) VALUES ('Αιθιοπία');
INSERT INTO nationality (name) VALUES ('Αϊτή');
INSERT INTO nationality (name) VALUES ('Ακτή Ελεφαντοστού');
INSERT INTO nationality (name) VALUES ('Αλβανία');
INSERT INTO nationality (name) VALUES ('Αλγερία');
INSERT INTO nationality (name) VALUES ('Ανγκόλα');
INSERT INTO nationality (name) VALUES ('Ανδόρα');
INSERT INTO nationality (name) VALUES ('Αντίγκουα και Μπαρμπούντα');
INSERT INTO nationality (name) VALUES ('Ανατολικό Τιμόρ');
INSERT INTO nationality (name) VALUES ('Αργεντινή');
INSERT INTO nationality (name) VALUES ('Αρμενία');
INSERT INTO nationality (name) VALUES ('Αυστραλία');
INSERT INTO nationality (name) VALUES ('Αυστρία');
INSERT INTO nationality (name) VALUES ('Αφγανιστάν');
INSERT INTO nationality (name) VALUES ('Βανουάτου');
INSERT INTO nationality (name) VALUES ('Βατικανό');
INSERT INTO nationality (name) VALUES ('Βέλγιο');
INSERT INTO nationality (name) VALUES ('Βενεζουέλα');
INSERT INTO nationality (name) VALUES ('Βιετνάμ');
INSERT INTO nationality (name) VALUES ('Βολιβία');
INSERT INTO nationality (name) VALUES ('Βόρεια Κορέα');
INSERT INTO nationality (name) VALUES ('Βόρεια Μακεδονία');
INSERT INTO nationality (name) VALUES ('Βοσνία και Ερζεγοβίνη');
INSERT INTO nationality (name) VALUES ('Βουλγαρία');
INSERT INTO nationality (name) VALUES ('Βραζιλία');
INSERT INTO nationality (name) VALUES ('Γαλλία');
INSERT INTO nationality (name) VALUES ('Γερμανία');
INSERT INTO nationality (name) VALUES ('Γεωργία');
INSERT INTO nationality (name) VALUES ('Γκάμπια');
INSERT INTO nationality (name) VALUES ('Γκαμπόν');
INSERT INTO nationality (name) VALUES ('Γκάνα');
INSERT INTO nationality (name) VALUES ('Γουατεμάλα');
INSERT INTO nationality (name) VALUES ('Γουιάνα');
INSERT INTO nationality (name) VALUES ('Γουινέα');
INSERT INTO nationality (name) VALUES ('Γουινέα-Μπισάου');
INSERT INTO nationality (name) VALUES ('Γρενάδα');
INSERT INTO nationality (name) VALUES ('Δανία');
INSERT INTO nationality (name) VALUES ('Δομινίκα');
INSERT INTO nationality (name) VALUES ('Δομινικανή Δημοκρατία');
INSERT INTO nationality (name) VALUES ('Ελ Σαλβαδόρ');
INSERT INTO nationality (name) VALUES ('Ελβετία');
INSERT INTO nationality (name) VALUES ('Ελλάδα');
INSERT INTO nationality (name) VALUES ('Ερυθραία');
INSERT INTO nationality (name) VALUES ('Εσθονία');
INSERT INTO nationality (name) VALUES ('Εσουατίνι');
INSERT INTO nationality (name) VALUES ('Ζάμπια');
INSERT INTO nationality (name) VALUES ('Ζιμπάμπουε');
INSERT INTO nationality (name) VALUES ('Ηνωμένα Αραβικά Εμιράτα');
INSERT INTO nationality (name) VALUES ('Ηνωμένο Βασίλειο');
INSERT INTO nationality (name) VALUES ('ΗΠΑ');
INSERT INTO nationality (name) VALUES ('Ιαπωνία');
INSERT INTO nationality (name) VALUES ('Ινδία');
INSERT INTO nationality (name) VALUES ('Ινδονησία');
INSERT INTO nationality (name) VALUES ('Ιορδανία');
INSERT INTO nationality (name) VALUES ('Ιράκ');
INSERT INTO nationality (name) VALUES ('Ιράν');
INSERT INTO nationality (name) VALUES ('Ιρλανδία');
INSERT INTO nationality (name) VALUES ('Ισημερινή Γουινέα');
INSERT INTO nationality (name) VALUES ('Ισημερινός');
INSERT INTO nationality (name) VALUES ('Ισλανδία');
INSERT INTO nationality (name) VALUES ('Ισπανία');
INSERT INTO nationality (name) VALUES ('Ισραήλ');
INSERT INTO nationality (name) VALUES ('Ιταλία');
INSERT INTO nationality (name) VALUES ('Καζακστάν');
INSERT INTO nationality (name) VALUES ('Καμερούν');
INSERT INTO nationality (name) VALUES ('Καμπότζη');
INSERT INTO nationality (name) VALUES ('Καναδάς');
INSERT INTO nationality (name) VALUES ('Κατάρ');
INSERT INTO nationality (name) VALUES ('Κεντροαφρικανική Δημοκρατία');
INSERT INTO nationality (name) VALUES ('Κένυα');
INSERT INTO nationality (name) VALUES ('Κίνα');
INSERT INTO nationality (name) VALUES ('Κιργιζία');
INSERT INTO nationality (name) VALUES ('Κιριμπάτι');
INSERT INTO nationality (name) VALUES ('Κολομβία');
INSERT INTO nationality (name) VALUES ('Κομόρες');
INSERT INTO nationality (name) VALUES ('Κονγκό (Δημοκρατία)');
INSERT INTO nationality (name) VALUES ('Κονγκό (Λαϊκή Δημοκρατία)');
INSERT INTO nationality (name) VALUES ('Κόστα Ρίκα');
INSERT INTO nationality (name) VALUES ('Κούβα');
INSERT INTO nationality (name) VALUES ('Κουβέιτ');
INSERT INTO nationality (name) VALUES ('Κροατία');
INSERT INTO nationality (name) VALUES ('Κύπρος');
INSERT INTO nationality (name) VALUES ('Λάος');
INSERT INTO nationality (name) VALUES ('Λετονία');
INSERT INTO nationality (name) VALUES ('Λευκορωσία');
INSERT INTO nationality (name) VALUES ('Λίβανος');
INSERT INTO nationality (name) VALUES ('Λιβερία');
INSERT INTO nationality (name) VALUES ('Λιβύη');
INSERT INTO nationality (name) VALUES ('Λιθουανία');
INSERT INTO nationality (name) VALUES ('Λιχτενστάιν');
INSERT INTO nationality (name) VALUES ('Λουξεμβούργο');
INSERT INTO nationality (name) VALUES ('Μαδαγασκάρη');
INSERT INTO nationality (name) VALUES ('Μαλαισία');
INSERT INTO nationality (name) VALUES ('Μαλάουι');
INSERT INTO nationality (name) VALUES ('Μαλδίβες');
INSERT INTO nationality (name) VALUES ('Μάλι');
INSERT INTO nationality (name) VALUES ('Μάλτα');
INSERT INTO nationality (name) VALUES ('Μαρόκο');
INSERT INTO nationality (name) VALUES ('Μαυρίκιος');
INSERT INTO nationality (name) VALUES ('Μαυριτανία');
INSERT INTO nationality (name) VALUES ('Μαυροβούνιο');
INSERT INTO nationality (name) VALUES ('Μεξικό');
INSERT INTO nationality (name) VALUES ('Μιανμάρ');
INSERT INTO nationality (name) VALUES ('Μικρονησία');
INSERT INTO nationality (name) VALUES ('Μογγολία');
INSERT INTO nationality (name) VALUES ('Μοζαμβίκη');
INSERT INTO nationality (name) VALUES ('Μολδαβία');
INSERT INTO nationality (name) VALUES ('Μονακό');
INSERT INTO nationality (name) VALUES ('Μπαγκλαντές');
INSERT INTO nationality (name) VALUES ('Μπαρμπάντος');
INSERT INTO nationality (name) VALUES ('Μπαχάμες');
INSERT INTO nationality (name) VALUES ('Μπαχρέιν');
INSERT INTO nationality (name) VALUES ('Μπελίζ');
INSERT INTO nationality (name) VALUES ('Μπενίν');
INSERT INTO nationality (name) VALUES ('Μποτσουάνα');
INSERT INTO nationality (name) VALUES ('Μπουρκίνα Φάσο');
INSERT INTO nationality (name) VALUES ('Μπουρούντι');
INSERT INTO nationality (name) VALUES ('Μπουτάν');
INSERT INTO nationality (name) VALUES ('Μπρουνέι');
INSERT INTO nationality (name) VALUES ('Ναμίμπια');
INSERT INTO nationality (name) VALUES ('Ναούρου');
INSERT INTO nationality (name) VALUES ('Νέα Ζηλανδία');
INSERT INTO nationality (name) VALUES ('Νεπάλ');
INSERT INTO nationality (name) VALUES ('Νίγηρας');
INSERT INTO nationality (name) VALUES ('Νιγηρία');
INSERT INTO nationality (name) VALUES ('Νικαράγουα');
INSERT INTO nationality (name) VALUES ('Νορβηγία');
INSERT INTO nationality (name) VALUES ('Νότια Αφρική');
INSERT INTO nationality (name) VALUES ('Νότια Κορέα');
INSERT INTO nationality (name) VALUES ('Νότιο Σουδάν');
INSERT INTO nationality (name) VALUES ('Ολλανδία');
INSERT INTO nationality (name) VALUES ('Ομάν');
INSERT INTO nationality (name) VALUES ('Ονδούρα');
INSERT INTO nationality (name) VALUES ('Ουγγαρία');
INSERT INTO nationality (name) VALUES ('Ουγκάντα');
INSERT INTO nationality (name) VALUES ('Ουζμπεκιστάν');
INSERT INTO nationality (name) VALUES ('Ουκρανία');
INSERT INTO nationality (name) VALUES ('Ουρουγουάη');
INSERT INTO nationality (name) VALUES ('Πακιστάν');
INSERT INTO nationality (name) VALUES ('Παλάου');
INSERT INTO nationality (name) VALUES ('Παναμάς');
INSERT INTO nationality (name) VALUES ('Παπούα Νέα Γουινέα');
INSERT INTO nationality (name) VALUES ('Παραγουάη');
INSERT INTO nationality (name) VALUES ('Περού');
INSERT INTO nationality (name) VALUES ('Πολωνία');
INSERT INTO nationality (name) VALUES ('Πορτογαλία');
INSERT INTO nationality (name) VALUES ('Πράσινο Ακρωτήριο');
INSERT INTO nationality (name) VALUES ('Ρουάντα');
INSERT INTO nationality (name) VALUES ('Ρουμανία');
INSERT INTO nationality (name) VALUES ('Ρωσία');
INSERT INTO nationality (name) VALUES ('Σαμόα');
INSERT INTO nationality (name) VALUES ('Σαουδική Αραβία');
INSERT INTO nationality (name) VALUES ('Σενεγάλη');
INSERT INTO nationality (name) VALUES ('Σερβία');
INSERT INTO nationality (name) VALUES ('Σεϋχέλλες');
INSERT INTO nationality (name) VALUES ('Σιέρα Λεόνε');
INSERT INTO nationality (name) VALUES ('Σινγκαπούρη');
INSERT INTO nationality (name) VALUES ('Σλοβακία');
INSERT INTO nationality (name) VALUES ('Σλοβενία');
INSERT INTO nationality (name) VALUES ('Σολομώντα Νησιά');
INSERT INTO nationality (name) VALUES ('Σομαλία');
INSERT INTO nationality (name) VALUES ('Σουδάν');
INSERT INTO nationality (name) VALUES ('Σουηδία');
INSERT INTO nationality (name) VALUES ('Σουρινάμ');
INSERT INTO nationality (name) VALUES ('Σρι Λάνκα');
INSERT INTO nationality (name) VALUES ('Συρία');
INSERT INTO nationality (name) VALUES ('Ταϊλάνδη');
INSERT INTO nationality (name) VALUES ('Τανζανία');
INSERT INTO nationality (name) VALUES ('Τατζικιστάν');
INSERT INTO nationality (name) VALUES ('Τζαμάικα');
INSERT INTO nationality (name) VALUES ('Τζιμπουτί');
INSERT INTO nationality (name) VALUES ('Τόγκο');
INSERT INTO nationality (name) VALUES ('Τόνγκα');
INSERT INTO nationality (name) VALUES ('Τουρκία');
INSERT INTO nationality (name) VALUES ('Τουρκμενιστάν');
INSERT INTO nationality (name) VALUES ('Τουβαλού');
INSERT INTO nationality (name) VALUES ('Τρινιντάντ και Τομπάγκο');
INSERT INTO nationality (name) VALUES ('Τσαντ');
INSERT INTO nationality (name) VALUES ('Τσεχία');
INSERT INTO nationality (name) VALUES ('Τυνησία');
INSERT INTO nationality (name) VALUES ('Υεμένη');
INSERT INTO nationality (name) VALUES ('Φιλιππίνες');
INSERT INTO nationality (name) VALUES ('Φινλανδία');
INSERT INTO nationality (name) VALUES ('Φίτζι');
INSERT INTO nationality (name) VALUES ('Χιλή');